"""Infrastructure 層的 Adapter：Markdown 報告生成。

將 :class:`~app.domain.entities.project.ProjectStructure` 轉換為
適合專案導讀與交接情境、具備高可讀性的 Markdown 文件。

當檔案總 Token 量超過 ``GLOBAL_TOKEN_BUDGET`` 時，透過
:class:`~app.infrastructure.adapters.content_compressor.ContentCompressor`
進行智慧壓縮，確保 LLM 上下文不會爆量。
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import List, Optional

from app.domain.entities.project import ProjectFile, ProjectStructure
from app.infrastructure.adapters.content_compressor import (
    CompressionResult,
    ContentCompressor,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Token 門檻值設定 (概略估算值)
# ---------------------------------------------------------------------------

#: 當檔案估算的 Token 數量超過此上限時，將會被截斷。
TOKEN_LIMIT: int = 2_000

#: 全域 Markdown 報告的 Token 預算上限。
#: 此數值為了配合 250k TPM 限制，設為 90,000 以容納兩次並行節點序列執行。
GLOBAL_TOKEN_BUDGET: int = 90_000

#: Token 估算常數：基於字元數的探測法，對 Gemini 而言較精準 (1 Token 約 3.5 字元)。
_CHARS_PER_TOKEN: float = 3.5


def _estimate_tokens(text: str) -> int:
    """估算 *text* 所佔用的 LLM Token 數量。

    使用基於字元數量的探測法 (``字元數 / 3.5``)，此方法對包含中文或程式碼
    等沒有明顯空白分隔的文本更為精確。

    Args:
        text: 欲估算的文字內容。

    Returns:
        估算的 Token 數量 (整數)。
    """
    return int(len(text) / _CHARS_PER_TOKEN)


def _truncate_content(content: str, limit: int = TOKEN_LIMIT) -> tuple[str, bool]:
    """截斷 *content* 以確保其估算的 Token 數量不超過 *limit*。

    Args:
        content: 完整的原始檔內容。
        limit: 允許的最大 Token 估算值。

    Returns:
        回傳一個 tuple ``(possibly_truncated_content, was_truncated)``，若內容
        實際上已被縮短，則 *was_truncated* 為 ``True``。
    """
    estimated = _estimate_tokens(content)
    if estimated <= limit:
        return content, False

    target_chars = int(limit * _CHARS_PER_TOKEN)
    truncated = content[:target_chars]
    return truncated, True


class MarkdownGenerator:
    """由 :class:`ProjectStructure` 物件產出結構化的 Markdown 報告。

    整合 :class:`ContentCompressor`，當檔案總量超過全域 Token 預算時
    自動壓縮，確保最終送入 LLM 的文本量可控。

    輸出的文件將遵循以下排版架構：

        # 📦 Project Report: <project_name>

        ## 🗂 Project Tree
        ```
        <目錄樹狀圖>
        ```

        ---
        *統計資料摘要*
        ---

        ## 📄 File: app/main.py
        ```python
        <檔案內容>
        ```

        … (針對每一個程式碼檔案重複此區塊)

        ---
        *壓縮統計（僅在壓縮觸發時出現）*

    Args:
        token_budget: 全域 Token 預算上限，預設使用 ``GLOBAL_TOKEN_BUDGET``。
    """

    def __init__(self, token_budget: Optional[int] = None) -> None:
        """初始化 MarkdownGenerator。

        Args:
            token_budget: 可選的自訂 Token 預算。若為 ``None`` 則使用全域預設值。
        """
        self._token_budget = token_budget or GLOBAL_TOKEN_BUDGET
        self._compressor = ContentCompressor(token_budget=self._token_budget)
        self._last_compression_result: Optional[CompressionResult] = None

    @property
    def last_compression_result(self) -> Optional[CompressionResult]:
        """取得最近一次 ``generate()`` 的壓縮結果（若有觸發壓縮）。

        Returns:
            :class:`CompressionResult` 或 ``None``（若未觸發壓縮）。
        """
        return self._last_compression_result

    def generate(self, structure: ProjectStructure) -> str:
        """產出完整的 Markdown 報告字串。

        若檔案總 Token 超過預算，會自動觸發壓縮流程，
        並在報告末尾附加壓縮統計區塊。

        Args:
            structure: 已經填滿資料的 :class:`ProjectStructure` Domain 實體。

        Returns:
            一段準備好回傳給 API 呼叫端或寫入磁碟的 UTF-8 Markdown 字串。
        """
        # ── 壓縮檢查：估算所有檔案的總 Token ──────────────────────────────
        compression_result = self._compressor.compress(structure.files)
        self._last_compression_result = compression_result

        # 決定最終使用的檔案列表
        render_files = compression_result.files
        is_compressed = len(compression_result.strategies_applied) > 0

        if is_compressed:
            logger.info(
                "[MarkdownGenerator] 壓縮已觸發：%d → %d Token（%s）",
                compression_result.original_token_estimate,
                compression_result.compressed_token_estimate,
                ", ".join(compression_result.strategies_applied),
            )

        sections: List[str] = []

        # ── 標題 (Header) ──────────────────────────────────────────────────
        sections.append(f"# 📦 Project Report: `{structure.project_name}`\n")
        sections.append(
            "> Auto-generated by **Project Handover Platform** — "
            "Phase 1: Project Deconstruction & Pre-processing\n"
        )

        # ── 專案目錄樹 (Project Tree) ────────────────────────────────────────
        sections.append("## 🗂 Project Tree\n")
        sections.append(f"```\n{structure.root_tree}\n```\n")

        # ── 統計資料 (Summary statistics) ──────────────────────────────────────
        sections.append("---\n")
        sections.append(
            f"| 指標 | 數值 |\n"
            f"|------|------|\n"
            f"| ZIP 內檔案總數 | {structure.total_files_in_zip} |\n"
            f"| 已過濾 / 忽略 | {structure.skipped_files} |\n"
            f"| 包含的程式碼檔案 | {len(render_files)} |\n"
        )
        sections.append("\n---\n")

        # ── 程式碼檔案區塊 (Code file sections) ──────────────────────────────
        for project_file in render_files:
            sections.append(self._render_file_section(project_file))

        # ── 壓縮統計區塊（僅在壓縮觸發時附加） ──────────────────────────────
        if is_compressed:
            sections.append(self._render_compression_stats(compression_result))

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # 私有輔助函式 (Private helpers)
    # ------------------------------------------------------------------

    def _render_file_section(self, project_file: ProjectFile) -> str:
        """在 Markdown 文件中渲染單一檔案的顯示區塊。

        Args:
            project_file: 欲被渲染的 :class:`ProjectFile` 實體。

        Returns:
            包含檔案標題與 Markdown 程式碼區塊 (fenced code block) 的字串。
        """
        lines: List[str] = []
        lines.append(f"## 📄 File: `{project_file.relative_path}`\n")

        fence = f"```{project_file.language}"
        lines.append(fence)
        lines.append(project_file.content)
        if project_file.is_truncated:
            lines.append(
                "\n<!-- [Content Truncated] "
                f"— 估算 Token 超過限制 -->"
            )
        lines.append("```\n")

        return "\n".join(lines)

    def _render_compression_stats(self, result: CompressionResult) -> str:
        """渲染壓縮統計區塊。

        Args:
            result: 壓縮執行結果。

        Returns:
            Markdown 格式的壓縮統計資訊。
        """
        compression_ratio = (
            (1 - result.compressed_token_estimate / result.original_token_estimate)
            * 100
            if result.original_token_estimate > 0
            else 0
        )

        return (
            "\n---\n\n"
            "## 📊 Token Budget Compression Report\n\n"
            "| 指標 | 數值 |\n"
            "|------|------|\n"
            f"| 原始估算 Token | {result.original_token_estimate:,} |\n"
            f"| 壓縮後估算 Token | {result.compressed_token_estimate:,} |\n"
            f"| 壓縮率 | {compression_ratio:.1f}% |\n"
            f"| 套用策略 | {', '.join(result.strategies_applied)} |\n"
            f"| AST Skeleton 提取 | {result.files_skeleton_extracted} 個檔案 |\n"
            f"| 優先級裁減 | {result.files_dropped} 個檔案 |\n"
            f"| 強制截斷 | {result.files_truncated} 個檔案 |\n"
        )


# ---------------------------------------------------------------------------
# 目錄樹產生器 (Directory tree builder)
# ---------------------------------------------------------------------------


def build_directory_tree(all_paths: List[str], project_name: str) -> str:
    """將扁平的路徑列表轉換為文字形式的目錄樹。

    輸出的格式將類似 Unix 系統中的 ``tree`` 指令：

        project-name/
        ├── app/
        │   ├── main.py
        │   └── utils.py
        └── README.md

    Args:
        all_paths: ZIP 當中所有的成員路徑 (包含即將被忽略的路徑)。
        project_name: 顯示於樹狀圖頂端的專案根目錄標籤。

    Returns:
        代表目錄樹的的多行字串。
    """
    # 建立一個巢狀的字典 (dict) 結構來代表目錄
    tree: dict = {}
    for raw_path in all_paths:
        parts = Path(raw_path).parts
        node = tree
        for part in parts:
            node = node.setdefault(part, {})

    lines: List[str] = [f"{project_name}/"]
    _render_tree_node(tree, lines, prefix="")
    return "\n".join(lines)


def _render_tree_node(
    node: dict,
    lines: List[str],
    prefix: str,
) -> None:
    """將 *node* 遞迴地渲染到 *lines* 列表中，並加上美觀的樹狀前綴線條。

    Args:
        node: 代表當前目錄層級的巢狀字典 (dict)。
        lines: 收集每行輸出字串的列表 (在函式內進行原地異動 mutate in-place)。
        prefix: 累積至目前的縮排前綴字串。
    """
    entries = sorted(node.keys())
    for idx, name in enumerate(entries):
        is_last = idx == len(entries) - 1
        connector = "└── " if is_last else "├── "
        child_node = node[name]
        # 若是目錄則必定有子節點；為了清晰起見，加上斜線後綴。
        is_dir = bool(child_node)
        display_name = f"{name}/" if is_dir else name
        lines.append(f"{prefix}{connector}{display_name}")

        if is_dir:
            extension = "    " if is_last else "│   "
            _render_tree_node(child_node, lines, prefix + extension)
