"""Infrastructure 層的 Adapter：Markdown 報告生成。

將 :class:`~app.domain.entities.project.ProjectStructure` 轉換為
適合專案導讀與交接情境、具備高可讀性的 Markdown 文件。
"""

from __future__ import annotations

from pathlib import Path
from typing import List

from app.domain.entities.project import ProjectFile, ProjectStructure

# ---------------------------------------------------------------------------
# Token 門檻值設定 (概略估算值)
# ---------------------------------------------------------------------------

#: 當檔案估算的 Token 數量超過此上限時，將會被截斷。
TOKEN_LIMIT: int = 2_000

#: 用於將單詞數量轉換為大致 Token 數的乘數。
TOKENS_PER_WORD: float = 1.3


def _estimate_tokens(text: str) -> int:
    """估算 *text* 所佔用的 LLM Token 數量。

    使用一個簡單基於單字數量的探測法 (``單字數 × 1.3``)，這個方法
    既快速又無需額外依賴套件，非常適合用來做為是否截斷的依據。

    Args:
        text: 欲估算的文字內容。

    Returns:
        估算的 Token 數量 (整數)。
    """
    return int(len(text.split()) * TOKENS_PER_WORD)


def _truncate_content(content: str, limit: int = TOKEN_LIMIT) -> tuple[str, bool]:
    """截斷 *content* 以確保其估算的 Token 數量不超過 *limit*。

    此函式會在單字邊界上進行截斷，以避免將單一 Token 從中切斷。

    Args:
        content: 完整的原始檔內容。
        limit: 允許的最大 Token 估算值。

    Returns:
        回傳一個 tuple ``(possibly_truncated_content, was_truncated)``，若內容
        實際上已被縮短，則 *was_truncated* 為 ``True``。
    """
    estimated = _estimate_tokens(content)
    if estimated <= limit:
        return content, False

    words = content.split()
    # 概略計算能夠容納於限制內的單字數量
    target_words = int(limit / TOKENS_PER_WORD)
    truncated = " ".join(words[:target_words])
    return truncated, True


class MarkdownGenerator:
    """由 :class:`ProjectStructure` 物件產出結構化的 Markdown 報告。

    輸出的文件將遵循以下排版架構：

        # 📦 Project Report: <project_name>

        ## 🗂 Project Tree
        ```
        <目錄樹狀圖>
        ```

        ---
        *統計資料摘要*
        ---

        ## 📄 File: app/main.py
        ```python
        <檔案內容>
        ```

        … (針對每一個程式碼檔案重複此區塊)
    """

    def generate(self, structure: ProjectStructure) -> str:
        """產出完整的 Markdown 報告字串。

        Args:
            structure: 已經填滿資料的 :class:`ProjectStructure` Domain 實體。

        Returns:
            一段準備好回傳給 API 呼叫端或寫入磁碟的 UTF-8 Markdown 字串。
        """
        sections: List[str] = []

        # ── 標題 (Header) ──────────────────────────────────────────────────
        sections.append(f"# 📦 Project Report: `{structure.project_name}`\n")
        sections.append(
            "> Auto-generated by **Project Handover Platform** — "
            "Phase 1: Project Deconstruction & Pre-processing\n"
        )

        # ── 專案目錄樹 (Project Tree) ────────────────────────────────────────
        sections.append("## 🗂 Project Tree\n")
        sections.append(f"```\n{structure.root_tree}\n```\n")

        # ── 統計資料 (Summary statistics) ──────────────────────────────────────
        sections.append("---\n")
        sections.append(
            f"| 指標 | 數值 |\n"
            f"|------|------|\n"
            f"| ZIP 內檔案總數 | {structure.total_files_in_zip} |\n"
            f"| 已過濾 / 忽略 | {structure.skipped_files} |\n"
            f"| 包含的程式碼檔案 | {structure.code_file_count} |\n"
        )
        sections.append("\n---\n")

        # ── 程式碼檔案區塊 (Code file sections) ──────────────────────────────
        for project_file in structure.files:
            sections.append(self._render_file_section(project_file))

        return "\n".join(sections)

    # ------------------------------------------------------------------
    # 私有輔助函式 (Private helpers)
    # ------------------------------------------------------------------

    def _render_file_section(self, project_file: ProjectFile) -> str:
        """在 Markdown 文件中渲染單一檔案的顯示區塊。

        Args:
            project_file: 欲被渲染的 :class:`ProjectFile` 實體。

        Returns:
            包含檔案標題與 Markdown 程式碼區塊 (fenced code block) 的字串。
        """
        lines: List[str] = []
        lines.append(f"## 📄 File: `{project_file.relative_path}`\n")

        fence = f"```{project_file.language}"
        lines.append(fence)
        lines.append(project_file.content)
        if project_file.is_truncated:
            lines.append(
                "\n<!-- [Content Truncated] "
                f"— 估算 Token 超過 {TOKEN_LIMIT} 限制 -->"
            )
        lines.append("```\n")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# 目錄樹產生器 (Directory tree builder)
# ---------------------------------------------------------------------------


def build_directory_tree(all_paths: List[str], project_name: str) -> str:
    """將扁平的路徑列表轉換為文字形式的目錄樹。

    輸出的格式將類似 Unix 系統中的 ``tree`` 指令：

        project-name/
        ├── app/
        │   ├── main.py
        │   └── utils.py
        └── README.md

    Args:
        all_paths: ZIP 當中所有的成員路徑 (包含即將被忽略的路徑)。
        project_name: 顯示於樹狀圖頂端的專案根目錄標籤。

    Returns:
        代表目錄樹的的多行字串。
    """
    # 建立一個巢狀的字典 (dict) 結構來代表目錄
    tree: dict = {}
    for raw_path in all_paths:
        parts = Path(raw_path).parts
        node = tree
        for part in parts:
            node = node.setdefault(part, {})

    lines: List[str] = [f"{project_name}/"]
    _render_tree_node(tree, lines, prefix="")
    return "\n".join(lines)


def _render_tree_node(
    node: dict,
    lines: List[str],
    prefix: str,
) -> None:
    """將 *node* 遞迴地渲染到 *lines* 列表中，並加上美觀的樹狀前綴線條。

    Args:
        node: 代表當前目錄層級的巢狀字典 (dict)。
        lines: 收集每行輸出字串的列表 (在函式內進行原地異動 mutate in-place)。
        prefix: 累積至目前的縮排前綴字串。
    """
    entries = sorted(node.keys())
    for idx, name in enumerate(entries):
        is_last = idx == len(entries) - 1
        connector = "└── " if is_last else "├── "
        child_node = node[name]
        # 若是目錄則必定有子節點；為了清晰起見，加上斜線後綴。
        is_dir = bool(child_node)
        display_name = f"{name}/" if is_dir else name
        lines.append(f"{prefix}{connector}{display_name}")

        if is_dir:
            extension = "    " if is_last else "│   "
            _render_tree_node(child_node, lines, prefix + extension)
